replicaCount: 1

image:
  repository: registry.dev.nudgebee.pollux.in/nudgebee-forager
  pullPolicy: IfNotPresent
  tag: 'latest'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

forager:
  relayURL: wss://relay.nudgebee.com/register
  accessKey: ''
  accessSecret: ''
  dataDir: /data
  signingPublicKey: ''

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
annotations: {}
