apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forager.fullname" . }}
  labels:
    {{- include "forager.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.forager.accessKey | b64enc | quote }}
  access-secret: {{ .Values.forager.accessSecret | b64enc | quote }}
